# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    executor: win/server-2019

    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout

      - run:
          name: "Checkout libsodium"
          command: git clone --branch stable https://github.com/jedisct1/libsodium.git

      - run:
          name: "MSYS Setup"
          command: |
            (New-Object System.Net.WebClient).DownloadFile('https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe', 'msys2.exe')
            .\msys2.exe -y -oC:\  # Extract to C:\msys64
            Remove-Item msys2.exe  # Delete the archive again

            $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
            $env:MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment

            # Update MSYS2
            C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'  # Core update (in case any core packages are outdated)
            C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'  # Normal update

            C:\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm zip make mingw-w64-x86_64-python mingw-w64-x86_64-qt5 wget mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5"

      - run:
          name: "Sodium build"
          command: |
            $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
            $env:MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment
            C:\msys64\usr\bin\bash -lc "cd /c/Users/circleci/project && ls && pushd libsodium && ./configure --enable-static --disable-shared && make -j`nproc` && make install && popd"

      - run:
          name: "MAME Build"
          command: |
            C:\msys64\usr\bin\bash -lc "cd /c/Users/circleci/project && MINGW64=/mingw64 make -j`nproc` MSBUILD=1 NO_USE_PORTAUDIO=1 PYTHON_EXECUTABLE=C:/msys64/mingw64/bin/python.exe vs2019 || MINGW64=/mingw64 make -j`nproc` MSBUILD=1 NO_USE_PORTAUDIO=1 PYTHON_EXECUTABLE=C:/msys64/mingw64/bin/python.exe vs2019"


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
