name: Build Linux

on:
  push:
    branches: [ mamehub, mamehub_libretro ]
  pull_request:
    branches: [ mamehub, mamehub_libretro ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update OS
      run: sudo apt-get install -y git build-essential python libsdl2-dev libsdl2-ttf-dev libfontconfig-dev qt5-default p7zip-full

    - uses: actions/checkout@v2
    
    - name: make
      run: make -j`nproc` SYMBOLS=1 SANITIZE=address && 7za ./mamehub_ubuntu_beta.7z ./mamehub64

    - name: Upload mame binary
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Linux Binary
        # A file, directory or wildcard pattern that describes what to upload
        path: ./mamehub_ubuntu_beta.7z
    
