name: Release

on:
    workflow_dispatch:

jobs:
    build_and_release_linux:
        runs-on: ubuntu-latest

        steps:
            - name: Update OS
              run: sudo apt update -y && sudo apt-get install -y git build-essential python3 libsdl2-dev libsdl2-ttf-dev libfontconfig-dev libpulse-dev qtbase5-dev qtbase5-dev-tools qtchooser qt5-qmake p7zip-full libsodium-dev

            - uses: actions/checkout@v2
              with:
                  submodules: "recursive"
                  path: "mame"

            - name: Update mamehub beta tag
              uses: richardsimko/update-tag@v1.0.10
              with:
                  tag_name: mamehub_beta_2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: make
              run: pushd mame && make -j2 && rm -Rf build .git src 3rdparty && ./mamehub -cc && mv mame.conf mame.conf.sample && popd

            - name: Upload mame binary
              uses: actions/upload-artifact@v2
              with:
                  # Artifact name
                  name: mamehub_ubuntu_beta
                  # A file, directory or wildcard pattern that describes what to upload
                  path: mame/*

            - name: Archive Release
              uses: thedoctor0/zip-release@0.7.1
              with:
                  type: "zip"
                  filename: "mamehub_ubuntu_beta.zip"
                  path: "mame"

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  body: |
                      New mamehub version.
                  files: mamehub_ubuntu_beta.zip
                  fail_on_unmatched_files: true
                  tag_name: mamehub_beta_2

    build_and_release_mac:
        runs-on: macos-latest

        steps:
            - name: Update OS
              run: brew update && brew install sdl2 sdl2_ttf openssl

            - uses: actions/checkout@v2
              with:
                  submodules: "recursive"
                  path: "mame"

            - uses: actions/checkout@v2
              with:
                  repository: spurious/SDL-mirror
                  ref: release-2.0.12
                  path: "sdl2"

            - name: make sdl2
              run: pushd sdl2 && ./configure --enable-static --disable-shared --prefix=$PWD/out && make && make install && popd

            - name: make mame
              run: pushd mame && make USE_LIBSDL=1 VERBOSE=1 SDL_INSTALL_ROOT=$PWD/../sdl2/out -j2 && rm -Rf build .git src 3rdparty && ./mamehub -cc && mv mame.conf mame.conf.sample && popd

            - name: Upload mame binary
              uses: actions/upload-artifact@v2
              with:
                  # Artifact name
                  name: mamehub_mac_beta
                  # A file, directory or wildcard pattern that describes what to upload
                  path: mame/*

            - name: Archive Release
              uses: thedoctor0/zip-release@0.7.1
              with:
                  type: "zip"
                  filename: "mamehub_mac_beta.zip"
                  path: "mame"

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  body: |
                      New mamehub version.
                  files: mamehub_mac_beta.zip
                  fail_on_unmatched_files: true
                  tag_name: mamehub_beta_2

    build_and_release_windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: "recursive"
                  path: "mame"

            - uses: actions/checkout@v2
              with:
                  repository: jedisct1/libsodium
                  ref: stable
                  path: "libsodium"

            - uses: msys2/setup-msys2@v2
              with:
                  update: true
                  release: false

            - shell: msys2 {0}
              run: |
                  pacman -Syu --noconfirm make mingw-w64-x86_64-python2 mingw-w64-x86_64-qt5 wget mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5
                  #wget -P /tmp  http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libs-9.3.0-2-any.pkg.tar.xz
                  #wget -P /tmp  http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-9.3.0-2-any.pkg.tar.xz
                  #pacman -U --noconfirm /tmp/*.tar.xz
                  pushd libsodium && ./configure --enable-static --disable-shared && make && make install && popd
                  pushd mame && MINGW64=/mingw64 make -j2 && rm -Rf build .git src 3rdparty && ./mamehub.exe -cc && mv mame.conf mame.conf.sample && popd

            - name: Upload mame binary
              uses: actions/upload-artifact@v2
              with:
                  # Artifact name
                  name: mamehub_windows_gcc_beta
                  # A file, directory or wildcard pattern that describes what to upload
                  path: mame/*

    build_and_release_windows_msvc:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: "recursive"
                  path: "mame"

            - uses: actions/checkout@v2
              with:
                  repository: jedisct1/libsodium
                  ref: stable
                  path: "libsodium"

            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.0.2

            - uses: msys2/setup-msys2@v2
              with:
                  update: true
                  release: false

            - shell: msys2 {0}
              run: |
                  pacman -Syu --noconfirm make mingw-w64-x86_64-python mingw-w64-x86_64-qt5 wget mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5
                  #wget -P /tmp  http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libs-9.3.0-2-any.pkg.tar.xz
                  #wget -P /tmp  http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-9.3.0-2-any.pkg.tar.xz
                  #pacman -U --noconfirm /tmp/*.tar.xz
                  pushd libsodium && ./configure --enable-static --disable-shared && make && make install && popd
                  pushd mame
                  export PATH="/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin:$PATH"
                  echo $PATH
                  rm -Rf .git
                  MINGW64=/mingw64 make -j2 MSBUILD=1 NO_USE_PORTAUDIO=1 PYTHON_EXECUTABLE=C:/msys64/mingw64/bin/python.exe vs2019 || MINGW64=/mingw64 make -j2 MSBUILD=1 NO_USE_PORTAUDIO=1 PYTHON_EXECUTABLE=C:/msys64/mingw64/bin/python.exe vs2019
                  rm -Rf build src 3rdparty && popd

            - name: Upload mame binary
              uses: actions/upload-artifact@v2
              with:
                  # Artifact name
                  name: mamehub_windows_msvc_beta
                  # A file, directory or wildcard pattern that describes what to upload
                  path: mame/*

            - name: Archive Release
              uses: thedoctor0/zip-release@0.7.1
              with:
                  type: "zip"
                  filename: "mamehub_windows_msvc_beta.zip"
                  path: "mame"

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  body: |
                      New mamehub version.
                  files: mamehub_windows_msvc_beta.zip
                  fail_on_unmatched_files: true
                  tag_name: mamehub_beta_2
